batch-processing/src/main/java/org/jboss/as/quickstarts/batch/model/Contact.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
 * contributors by the @authors tag. See the copyright.txt in the
 * distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.as.quickstarts.batch.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

@Entity
public class Contact {

    @Id
    private Integer id;

    @NotNull
    @Column(unique = true)
    private String name;

    @NotNull
    private String phone;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        return "Contact [id=" + id + ", name=" + name + ", phone=" + phone + "]";
    }

}

batch-processing/src/main/java/org/jboss/as/quickstarts/batch/controller/BatchController.java
/*
 * JBoss, Home of Professional Open Source
 * Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
 * contributors by the @authors tag. See the copyright.txt in the
 * distribution for a full listing of individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.jboss.as.quickstarts.batch.controller;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Logger;

import javax.batch.operations.JobOperator;
import javax.batch.operations.NoSuchJobException;
import javax.batch.runtime.BatchRuntime;
import javax.batch.runtime.JobExecution;
import javax.batch.runtime.JobInstance;
import javax.enterprise.inject.Model;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

import org.apache.commons.lang3.RandomStringUtils;

//The @Model stereotype is a convenience mechanism to make this a request-scoped bean that has an
//EL name
//Read more about the @Model stereotype in this FAQ:
//http://www.cdi-spec.org/faq/#accordion6
@Model
public class BatchController {

    @Inject
    private FacesContext facesContext;

    @Inject
    private Logger log;

    private String fileName = "temp-file.txt";

    private boolean generateWithError;

    @Min(0)
    @Max(1000000)
    private Integer numRecords = 10;

    public void generate() throws IOException {
        File tempFile = new File(System.getProperty("java.io.tmpdir"), fileName);
        try (BufferedWriter bos = new BufferedWriter(new FileWriter(tempFile, false))) {
            log.info("Starting to generate " + numRecords + " records in file " + tempFile);
            String previousName = null;
            for (int x = 0; x < numRecords; x++) {
                String name = RandomStringUtils.randomAlphabetic(10);
                String phone = RandomStringUtils.randomNumeric(9);
                // Generate a duplicate name;
                if (generateWithError && x == (numRecords / 2)) {
                    name = previousName;
                }
                String record = (x + 1) + "|" + name + "|" + phone;
                bos.write(record + "\n");
                previousName = name;
            }
            log.info("File generated at " + tempFile);
            facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO,
                "File generated with " + numRecords + " records to be imported. File name: " + getFileName(), null));
            if (generateWithError) {
                facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Attention: This file contains duplicate records for test purpose.", null));
            }
        }
    }

    public void generateFileAndStarJob() throws IOException {
        generate();
        startImport();
    }

    public void startImport() {
        JobOperator jobOperator = BatchRuntime.getJobOperator();
        Properties jobParameters = new Properties();
        jobParameters.setProperty("fileName", getFileName());
        long execID = jobOperator.start("import-file", jobParameters);
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, "New job execution #" + execID + " running. Importing file:" + getFileName(), null));
    }

    public Set<JobData> getJobsExecution() {
        Set<JobData> jobsData = new TreeSet<JobData>(new Comparator<JobData>() {

            @Override
            public int compare(JobData o1, JobData o2) {
                return o2.getJobInstanceId().compareTo(o1.getJobInstanceId());
            }
        });
        Map<Long, JobExecution> jobIntances = new HashMap<>();
        JobOperator jobOperator = BatchRuntime.getJobOperator();
        try {
            List<JobInstance> instances = jobOperator.getJobInstances("import-file", 0, jobOperator.getJobInstanceCount("import-file"));
            for (JobInstance ji : instances) {
                List<JobExecution> executions = jobOperator.getJobExecutions(ji);
                for (JobExecution jobExecution : executions) {
                    // initialize the map if null
                    if (jobIntances.get(ji.getInstanceId()) == null) {
                        jobIntances.put(ji.getInstanceId(), jobExecution);
                    }
                    // Update the jobExecution if is newer
                    JobExecution existing = jobIntances.get(ji.getInstanceId());
                    if (jobExecution.getExecutionId() > existing.getExecutionId()) {
                        jobIntances.put(ji.getInstanceId(), jobExecution);
                    }
                }
            }
            for (Long instaceId : jobIntances.keySet()) {
                JobExecution jobExecution = jobIntances.get(instaceId);
                JobInstance ji = jobOperator.getJobInstance(jobExecution.getExecutionId());
                Properties parameters = jobOperator.getParameters(jobExecution.getExecutionId());
                jobsData.add(new JobData(ji.getInstanceId(), jobExecution.getExecutionId(), ji.getJobName(), jobExecution.getCreateTime(), jobExecution.getEndTime(), jobExecution
                    .getBatchStatus(), parameters, jobExecution.getExitStatus()));
            }
        } catch (NoSuchJobException e) {
            // It's ok if when doesn't have any jobs yet to show
        }

        return jobsData;
    }

    public void restartJob(int executionId) {
        JobOperator jobOperator = BatchRuntime.getJobOperator();
        Properties jobParameters = jobOperator.getParameters(executionId);
        jobParameters.setProperty("restartedOnce", "true");
        long newExecutionId = jobOperator.restart(executionId, jobParameters);
        facesContext.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Execution " + executionId + " restarted! New execution id: " + newExecutionId, null));
    }

    public Integer getNumRecords() {
        return numRecords;
    }

    public void setNumRecords(Integer numRecords) {
        this.numRecords = numRecords;
    }

    public boolean isGenerateWithError() {
        return generateWithError;
    }

    public void setGenerateWithError(boolean generateWithError) {
        this.generateWithError = generateWithError;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
}

batch-processing/src/main/webapp/batch.xhtml
<!--
    JBoss, Home of Professional Open Source
    Copyright 2015, Red Hat, Inc. and/or its affiliates, and individual
    contributors by the @authors tag. See the copyright.txt in the
    distribution for a full listing of individual contributors.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
>
<h:head>
    <title>Batch Processing</title>
    <link rel="stylesheet" href="css/patternfly.css"/>
    <link rel="stylesheet" href="css/font-awesome.css"/>
    <script src="js/jquery-2.0.3.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"/>
</h:head>
<body>
    <h:form id="form" styleClass="form-horizontal">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h2>Generate a import file</h2>
                    This form will generate a file with the number of records specified.
                    <div class="form-group">
                        <h:outputLabel value="File name:" styleClass="col-sm-5 control-label" />
                        <div class="col-sm-5">
                            <h:inputText id="fileName" value="#{batchController.fileName}" />
                            <h:message for="fileName" styleClass="help-block" />
                         </div>
                    </div>
                    <div class="form-group">
                        <h:outputLabel value="Number of records:" styleClass="col-sm-5 control-label" />
                        <div class="col-sm-5">
                            <h:inputText id="numRecords" value="#{batchController.numRecords}" >
                                <f:convertNumber integerOnly="true" />
                            </h:inputText>
                            <h:message for="numRecords" styleClass="help-block" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-7">
                            <h:selectBooleanCheckbox value="#{batchController.generateWithError}" />
                            Generate a duplicate record (forced error)
                        </div>
                    </div>
                    <div class="btn-group-vertical">
                            <h:commandButton styleClass="btn btn-default btn-sm" action="#{batchController.generateFileAndStarJob()}" value="Generate a new file and start import job" >
                                <f:ajax execute="@form" render="@form"/>
                            </h:commandButton>
                            <h:commandButton styleClass="btn btn-default btn-sm" action="#{batchController.generate()}" value="Generate new file" >
                                <f:ajax execute="@form" render="@form"/>
                            </h:commandButton>
                            <h:commandButton styleClass="btn btn-default btn-sm" action="#{batchController.startImport()}" value="Start import Job" >
                                <f:ajax execute="@form"  render="@form"/>
                            </h:commandButton>
                    </div>
                    <div style="padding-top: 3em;">
                        <h:messages globalOnly="true" errorStyle="color: red;" warnStyle="color: yellow;"/>
                    </div>
                </div>
                <div class="col-md-8">
                    <h2>Instructions</h2>
                    <h3>Usage 1: Import the file without any errors</h3>
                     Click on <strong>Generate a new file and start import job</strong> button. This will generate a new file with 10 unique records to be imported. After the file is generated, the import job will start. You will see a table containing information about the task that was just started. You can click on <strong>Update jobs list</strong> button and verify that the job was completed.
                     
                     <h3>Usage 2: Import an error file and fix it</h3>
                     Check the <strong>Generate a duplicate record</strong> checkbox and click on <strong>Generate a new file and start import job</strong> button. If you click on <strong>Update jobs list</strong> button, you will see that the job failed with the following Exit Status: <em>Error : org.hibernate.exception.ConstraintViolationException: could not execute statement</em>. This was caused because the job tried to insert a duplicate record at the Database. You will also see `org.h2.jdbc.JdbcSQLException: Unique index or primary key violation` exception stacktraces in the server log.
                     Uncheck the <strong>Generate a duplicate record</strong> checkbox and click on <strong>Generate a new file</strong> button. This will generate file without errors.
                     Click on <strong>Restart</strong> button in the last column for that job instance in the <strong>List of Jobs</strong> table. If you  click on <strong>Update jobs list</strong> button to verify that the job was completed. Analyze the logs and check that the job started from the last checkpoint.
                    
                     <h3>Usage 3: Import an error file and do not fix the errors </h3>
                     Check the <strong>Generate a duplicate record</strong> checkbox and click on <strong>Generate a new file and start import job</strong> button. If you click on <strong>Update jobs list</strong> button, you will see that the job failed with the following Exit Status: <em>Error : org.hibernate.exception.ConstraintViolationException: could not execute statement</em>. This was caused because the job tried to insert a duplicate record at the Database.
                     Just click on <strong>Restart</strong> button again. If you  click on <strong>Update jobs list</strong> button, you will see that the job was marked as <strong>ABANDONED</strong> this time because it was restarted once. Notice that there's a new parameter: `restartedOnce=true`.
                </div>
            </div>
            <hr />
            <div class="row">
                    <h2>List of Jobs</h2>
                    <br />
                    <h:commandButton id="refreshButton" styleClass="btn btn-default"  value="Update jobs list" >
                        <f:ajax execute="@this" render="@form"/>
                    </h:commandButton>
                    <h:dataTable id="dataTable" value="#{batchController.jobsExecution}" var="job" width="100%" style="text-align: center;" border="1"
                        rendered="#{batchController.jobsExecution.size() > 0}"
                        styleClass="table table-striped table-bordered table-hover">
                        <h:column>
                            <f:facet name="header">Instance Id</f:facet>
                            #{job.jobInstanceId}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Execution Id</f:facet>
                            #{job.executionId}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Parameters</f:facet>
                            #{job.jobParameters}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Start Time</f:facet>
                            <h:outputText value="#{job.startTime}">
                                <f:convertDateTime type="time" timeZone="#{timeZone}" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">End Time</f:facet>
                            <h:outputText value="#{job.endTime}">
                                <f:convertDateTime type="time" timeZone="#{timeZone}" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">Batch status</f:facet>
                            #{job.batchStatus}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Exit status</f:facet>
                            #{job.exitStatus}
                        </h:column>
                        <h:column>
                            <f:facet name="header">Operation</f:facet>
                            <h:commandButton value="Restart" rendered="#{job.batchStatus == 'FAILED'}"
                                action="#{batchController.restartJob(job.executionId)}">
                                <f:ajax render="@form"/>
                            </h:commandButton>
                        </h:column>
                </h:dataTable>
            </div>
        </div>
    </h:form>
</body>
</html>